import { StyleSheet, Dimensions, Platform } from 'react-native';
import { theme } from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.main,
  },
  headerContainer: {
    height: 280,
    width: '100%',
    position: 'relative',
  },
  coverImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 40,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  contentSheet: {
    flex: 1,
    backgroundColor: theme.colors.background.main,
    marginTop: -32,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 40,
  },
  groupName: {
    fontSize: 24,
    fontFamily: theme.fontFamily.bold,
    color: theme.colors.text.heading,
    marginBottom: 8,
  },
  groupMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  groupTag: {
    backgroundColor: theme.colors.brand.primary + '20',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 12,
  },
  groupTagText: {
    color: theme.colors.brand.primary,
    fontFamily: theme.fontFamily.bold,
    fontSize: 12,
  },
  memberCount: {
    color: theme.colors.text.muted,
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: theme.fontFamily.bold,
    color: theme.colors.text.heading,
    marginTop: 24,
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    color: theme.colors.text.body,
    lineHeight: 24,
    fontFamily: theme.fontFamily.regular,
  },
  participantsContainer: {
    marginBottom: 10,
  },
  participantsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addMemberButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: theme.colors.brand.primary,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background.input,
    marginRight: -12,
    zIndex: 10,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: theme.colors.background.main,
    marginLeft: -16,
  },
  moreParticipants: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.background.input,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -16,
    borderWidth: 2,
    borderColor: theme.colors.background.main,
  },
  moreText: {
    fontSize: 14,
    fontFamily: theme.fontFamily.bold,
    color: theme.colors.text.muted,
  },
  challengesContainer: {
    marginBottom: 32,
  },
  challengeCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.background.input,
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
  },
  challengeImage: {
    width: 60,
    height: 80,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  challengeContent: {
    flex: 1,
    marginLeft: 16,
  },
  challengeTitle: {
    fontSize: 16,
    fontFamily: theme.fontFamily.bold,
    color: theme.colors.text.heading,
    marginBottom: 4,
  },
  challengeMeta: {
    fontSize: 12,
    color: theme.colors.brand.primary,
    fontFamily: theme.fontFamily.bold,
    marginBottom: 2,
  },
  challengeDesc: {
    fontSize: 12,
    color: theme.colors.text.muted,
    fontFamily: theme.fontFamily.regular,
  },
  actionButton: {
    backgroundColor: theme.colors.brand.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 16,
    marginTop: 16,
    marginBottom: Platform.OS === 'ios' ? 20 : 0,
    shadowColor: theme.colors.brand.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  actionButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: theme.fontFamily.bold,
    marginLeft: 8,
  }
});